services:
  - type: web
    name: unity-discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: starter
    autoDeploy: false
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false